# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-memorydb
  description: This component provisions an AWS MemoryDB cluster
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component






